vector-agent:
  image:
    # Use the latest release image.
    version: latest

  env:
    # Set the log level reasonably high.
    - name: LOG
      value: info

  extraConfigDirSources:
    - configMap:
        name: vector-agent-config
        optional: true
    - secret:
        name: vector-agent-config
        optional: true

vector-aggregator:
  extraConfigDirSources:
    - configMap:
        name: vector-aggregator-config
        optional: true
    - secret:
        name: vector-aggregator-config
        optional: true
