global:

  vector:
    image:
      # Use the latest release image.
      version: latest

    commonEnvKV:
      # Set the log level reasonably high.
      LOG: info

vector-agent:
  extraConfigDirSources:
    - configMap:
        name: vector-agent-config
        optional: true
    - secret:
        name: vector-agent-config
        optional: true

vector-aggregator:
  extraConfigDirSources:
    - configMap:
        name: vector-aggregator-config
        optional: true
    - secret:
        name: vector-aggregator-config
        optional: true
